import { chromium } from 'playwright';
import { waitPlayerIdentity } from './browser-smoke-helpers.mjs';
import { writeFile } from 'node:fs/promises';
const url = process.env.BABBLE_URL || 'http://127.0.0.1:3117';
const out = process.env.OUT || 'tmp/our-gameplay.png';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', e => errors.push(String(e)));
page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
await page.goto(url, { waitUntil: 'domcontentloaded' });
await waitPlayerIdentity(page);
await page.locator('button', { hasText: /create room/i }).click({ force: true, timeout: 8000 });
await page.waitForTimeout(1000);
await page.evaluate(() => {
  const b = [...document.querySelectorAll('button')].find(x => /start/i.test(x.textContent || ''));
  if (!b) throw new Error('Start match button not found');
  b.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }));
  b.dispatchEvent(new PointerEvent('pointerup', { bubbles: true }));
  b.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true, view: window }));
});
await page.waitForFunction(() => /planning/.test(document.body.innerText), null, { timeout: 8000 });
await page.waitForTimeout(1600);
const text = await page.locator('body').innerText().catch(()=>'');
const canvasData = await page.evaluate(() => {
  const c = document.querySelector('canvas');
  return c ? c.toDataURL('image/png') : null;
});
if (!canvasData) throw new Error('No canvas found');
await writeFile(out, Buffer.from(canvasData.split(',')[1], 'base64'));
console.log(JSON.stringify({ out, errors, text: text.slice(0, 300) }, null, 2));
await browser.close();
